//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input Action/PlayerActionInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActionInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActionInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActionInput"",
    ""maps"": [
        {
            ""name"": ""InputPlayerAction"",
            ""id"": ""d4ee359b-2cd3-4473-87c1-4692c2c35148"",
            ""actions"": [
                {
                    ""name"": ""Shooting"",
                    ""type"": ""Button"",
                    ""id"": ""a1a66122-41d9-44eb-bcb9-373f4612dc40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SilentKill"",
                    ""type"": ""Button"",
                    ""id"": ""7bdecdc9-0fd9-456e-8d18-b74c23c791e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangingWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""00348e2f-2196-4c42-a40d-c98ec9b89632"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangePlayer"",
                    ""type"": ""Button"",
                    ""id"": ""071fe5e1-7e58-418d-82fa-ed09c5893767"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scope"",
                    ""type"": ""Button"",
                    ""id"": ""67bb825e-50c3-401d-9d2a-5ca407012fe9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""5ae68d93-695a-4e4d-9a7c-fba775db84a6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""709ab3e1-5252-4e58-9ddb-e56098262fb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""a2ffa34d-e2f1-47da-b70d-bbd465b15076"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""e9c2ab17-b3b3-482d-accb-22c030686088"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Command"",
                    ""type"": ""Button"",
                    ""id"": ""1ec604b5-4781-4d40-8e48-83ff417424dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnCommand"",
                    ""type"": ""Button"",
                    ""id"": ""f2362205-11ac-4c79-b536-7e3b70145197"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldPosition"",
                    ""type"": ""Button"",
                    ""id"": ""a9cb49e1-b57b-4b41-a8d4-62092f74a2d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnHoldPosition"",
                    ""type"": ""Button"",
                    ""id"": ""0a4e3c02-b9d2-42ef-8d1c-f6fe3c18ca50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CommandFriend1"",
                    ""type"": ""Button"",
                    ""id"": ""fcb6ce12-f4b2-42f6-a5ef-57df6ada4e8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CommandFriend2"",
                    ""type"": ""Button"",
                    ""id"": ""33d23430-c250-4460-850e-2f962a033942"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitCommand"",
                    ""type"": ""Button"",
                    ""id"": ""93be8564-6b13-4a85-bea0-d938476786aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RegroupFriend"",
                    ""type"": ""Button"",
                    ""id"": ""e684fd00-42a9-45e1-824c-5d96317f38b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""44403a63-af6d-400c-b989-041ffc7ba145"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillButton"",
                    ""type"": ""Button"",
                    ""id"": ""7579b67e-6e66-4fe5-8f32-a21a83d7a398"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Whistle"",
                    ""type"": ""Button"",
                    ""id"": ""867fd6f3-cc8d-40d8-82bd-22ee705ded89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NightVision"",
                    ""type"": ""Button"",
                    ""id"": ""fc427d59-c9d3-4f11-89aa-58cc4e6f4251"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""ff3ff4b7-33b9-4dd5-989c-c1729097b8bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeCover"",
                    ""type"": ""Button"",
                    ""id"": ""07abd21f-c337-4390-832b-23c447f04485"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitTakeCover"",
                    ""type"": ""Button"",
                    ""id"": ""c8be7bf7-959d-4f29-b4be-8ba47fe853b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Command Friend"",
                    ""type"": ""Button"",
                    ""id"": ""882bfb27-e90b-4080-8262-2f3fb5c649b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeCameraPlace"",
                    ""type"": ""Button"",
                    ""id"": ""51e9138b-e174-4510-b83c-9a22eaeb70af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Immortalized"",
                    ""type"": ""Button"",
                    ""id"": ""a95e2315-efc8-41bd-9e6d-b9971e8e1845"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""48981095-f568-4301-981c-8525f9220f63"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce50390c-ee25-4867-8064-458229c96c72"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SilentKill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1c05c04-dee4-44f3-9329-624685e571ec"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangingWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62738c04-e284-4457-8049-049aeb8de3dd"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7bca3d4-785c-43d2-92a5-8c920d738d7b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scope"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9a8c5271-1f20-466d-9166-97da362fafba"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ed510a29-e23b-4b04-a517-f9d2ed64d0b7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""914f02ea-3029-446a-a05a-428b4995fda4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""85487b36-d284-4240-abda-3d058b115087"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""eda68aeb-b1f6-4359-b924-de6a00bdf5b5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""66628e6c-17d0-457a-8e93-d1bc9b5dc5d5"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""171cce9c-8a53-467b-82e3-0ca64e783415"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a973222-8b41-4b6a-9ca0-f9c2fb631734"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c6b6b74-b75c-4802-a5fe-e62fdfcdc78f"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Command"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2683275f-ef13-4cc8-ab81-71959eda5000"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9fa93b2-0119-46ef-92c4-3f0fd1c057c2"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f48e8ad4-d1d1-473e-8c54-f4ee456d2a86"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnHoldPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f3e16bd-c721-4aba-8d18-89ac95e25f2d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8a77be8-faad-4d6d-b4fb-11793bee0786"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fac45b6b-e6cd-4c43-8eef-51a3dcea0633"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Whistle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9920ae0b-8d2d-4c44-bf96-86f1558d8c1a"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NightVision"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7959ed7-cc80-4d9e-af2b-02106a9f5926"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommandFriend2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fe09bb1-fd1d-45d7-a438-2c8be20635a1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommandFriend1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f59f7b38-3d4b-4adf-85fe-825f7ef64e12"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RegroupFriend"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1be8e208-dde3-43c4-b874-86b4ce71ac13"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b13c8174-9a92-4d4c-8c20-61c224a43a95"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2ba94b7-a3a2-433b-bf65-8834cf5aae40"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeCover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""340da7be-b49a-4347-a6dc-80b37a0d7819"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitTakeCover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0055b4fc-bedf-48b6-9ca3-46285ae9b673"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Command Friend"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f18b553d-00ee-4119-9905-2aebcf317c40"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCameraPlace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""85fa07cb-ce92-46ba-9230-f1c85183fc88"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Immortalized"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""639ce7dc-8997-454f-8322-9f70de201ed7"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Immortalized"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""c538cd58-2aaa-488a-94d4-8d4bcee28de2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Immortalized"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""784524ed-cfda-4231-bdbf-461fbfb7d8d8"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Immortalized"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""InputMenuAction"",
            ""id"": ""363ea8e6-5e94-484b-9b46-6339b9b30448"",
            ""actions"": [
                {
                    ""name"": ""Pause Game"",
                    ""type"": ""Button"",
                    ""id"": ""b487965e-dbf4-4a47-9ce0-6adae10cdf0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitSettingsMainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""94806917-2bd8-41d5-9b4f-a3f5479238a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Command Button"",
                    ""type"": ""Value"",
                    ""id"": ""4a4986d8-d9cf-418c-8243-d7164f37481d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3283999-b572-4261-b807-5859934a9227"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""3953109a-074b-43b7-b48f-8d1e21c0c8fe"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Command Button"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1955f498-a997-49fe-aefc-c8c41666a487"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Command Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""480795b1-f237-4707-8eec-74a4a07c1b5b"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Command Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5cef0d72-b3c8-4eee-a0a8-6de3ea4d9316"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitSettingsMainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InputPlayerAction
        m_InputPlayerAction = asset.FindActionMap("InputPlayerAction", throwIfNotFound: true);
        m_InputPlayerAction_Shooting = m_InputPlayerAction.FindAction("Shooting", throwIfNotFound: true);
        m_InputPlayerAction_SilentKill = m_InputPlayerAction.FindAction("SilentKill", throwIfNotFound: true);
        m_InputPlayerAction_ChangingWeapon = m_InputPlayerAction.FindAction("ChangingWeapon", throwIfNotFound: true);
        m_InputPlayerAction_ChangePlayer = m_InputPlayerAction.FindAction("ChangePlayer", throwIfNotFound: true);
        m_InputPlayerAction_Scope = m_InputPlayerAction.FindAction("Scope", throwIfNotFound: true);
        m_InputPlayerAction_Movement = m_InputPlayerAction.FindAction("Movement", throwIfNotFound: true);
        m_InputPlayerAction_Crouch = m_InputPlayerAction.FindAction("Crouch", throwIfNotFound: true);
        m_InputPlayerAction_Run = m_InputPlayerAction.FindAction("Run", throwIfNotFound: true);
        m_InputPlayerAction_Reload = m_InputPlayerAction.FindAction("Reload", throwIfNotFound: true);
        m_InputPlayerAction_Command = m_InputPlayerAction.FindAction("Command", throwIfNotFound: true);
        m_InputPlayerAction_UnCommand = m_InputPlayerAction.FindAction("UnCommand", throwIfNotFound: true);
        m_InputPlayerAction_HoldPosition = m_InputPlayerAction.FindAction("HoldPosition", throwIfNotFound: true);
        m_InputPlayerAction_UnHoldPosition = m_InputPlayerAction.FindAction("UnHoldPosition", throwIfNotFound: true);
        m_InputPlayerAction_CommandFriend1 = m_InputPlayerAction.FindAction("CommandFriend1", throwIfNotFound: true);
        m_InputPlayerAction_CommandFriend2 = m_InputPlayerAction.FindAction("CommandFriend2", throwIfNotFound: true);
        m_InputPlayerAction_ExitCommand = m_InputPlayerAction.FindAction("ExitCommand", throwIfNotFound: true);
        m_InputPlayerAction_RegroupFriend = m_InputPlayerAction.FindAction("RegroupFriend", throwIfNotFound: true);
        m_InputPlayerAction_Interact = m_InputPlayerAction.FindAction("Interact", throwIfNotFound: true);
        m_InputPlayerAction_SkillButton = m_InputPlayerAction.FindAction("SkillButton", throwIfNotFound: true);
        m_InputPlayerAction_Whistle = m_InputPlayerAction.FindAction("Whistle", throwIfNotFound: true);
        m_InputPlayerAction_NightVision = m_InputPlayerAction.FindAction("NightVision", throwIfNotFound: true);
        m_InputPlayerAction_Throw = m_InputPlayerAction.FindAction("Throw", throwIfNotFound: true);
        m_InputPlayerAction_TakeCover = m_InputPlayerAction.FindAction("TakeCover", throwIfNotFound: true);
        m_InputPlayerAction_ExitTakeCover = m_InputPlayerAction.FindAction("ExitTakeCover", throwIfNotFound: true);
        m_InputPlayerAction_CommandFriend = m_InputPlayerAction.FindAction("Command Friend", throwIfNotFound: true);
        m_InputPlayerAction_ChangeCameraPlace = m_InputPlayerAction.FindAction("ChangeCameraPlace", throwIfNotFound: true);
        m_InputPlayerAction_Immortalized = m_InputPlayerAction.FindAction("Immortalized", throwIfNotFound: true);
        // InputMenuAction
        m_InputMenuAction = asset.FindActionMap("InputMenuAction", throwIfNotFound: true);
        m_InputMenuAction_PauseGame = m_InputMenuAction.FindAction("Pause Game", throwIfNotFound: true);
        m_InputMenuAction_ExitSettingsMainMenu = m_InputMenuAction.FindAction("ExitSettingsMainMenu", throwIfNotFound: true);
        m_InputMenuAction_SelectCommandButton = m_InputMenuAction.FindAction("Select Command Button", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InputPlayerAction
    private readonly InputActionMap m_InputPlayerAction;
    private List<IInputPlayerActionActions> m_InputPlayerActionActionsCallbackInterfaces = new List<IInputPlayerActionActions>();
    private readonly InputAction m_InputPlayerAction_Shooting;
    private readonly InputAction m_InputPlayerAction_SilentKill;
    private readonly InputAction m_InputPlayerAction_ChangingWeapon;
    private readonly InputAction m_InputPlayerAction_ChangePlayer;
    private readonly InputAction m_InputPlayerAction_Scope;
    private readonly InputAction m_InputPlayerAction_Movement;
    private readonly InputAction m_InputPlayerAction_Crouch;
    private readonly InputAction m_InputPlayerAction_Run;
    private readonly InputAction m_InputPlayerAction_Reload;
    private readonly InputAction m_InputPlayerAction_Command;
    private readonly InputAction m_InputPlayerAction_UnCommand;
    private readonly InputAction m_InputPlayerAction_HoldPosition;
    private readonly InputAction m_InputPlayerAction_UnHoldPosition;
    private readonly InputAction m_InputPlayerAction_CommandFriend1;
    private readonly InputAction m_InputPlayerAction_CommandFriend2;
    private readonly InputAction m_InputPlayerAction_ExitCommand;
    private readonly InputAction m_InputPlayerAction_RegroupFriend;
    private readonly InputAction m_InputPlayerAction_Interact;
    private readonly InputAction m_InputPlayerAction_SkillButton;
    private readonly InputAction m_InputPlayerAction_Whistle;
    private readonly InputAction m_InputPlayerAction_NightVision;
    private readonly InputAction m_InputPlayerAction_Throw;
    private readonly InputAction m_InputPlayerAction_TakeCover;
    private readonly InputAction m_InputPlayerAction_ExitTakeCover;
    private readonly InputAction m_InputPlayerAction_CommandFriend;
    private readonly InputAction m_InputPlayerAction_ChangeCameraPlace;
    private readonly InputAction m_InputPlayerAction_Immortalized;
    public struct InputPlayerActionActions
    {
        private @PlayerActionInput m_Wrapper;
        public InputPlayerActionActions(@PlayerActionInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shooting => m_Wrapper.m_InputPlayerAction_Shooting;
        public InputAction @SilentKill => m_Wrapper.m_InputPlayerAction_SilentKill;
        public InputAction @ChangingWeapon => m_Wrapper.m_InputPlayerAction_ChangingWeapon;
        public InputAction @ChangePlayer => m_Wrapper.m_InputPlayerAction_ChangePlayer;
        public InputAction @Scope => m_Wrapper.m_InputPlayerAction_Scope;
        public InputAction @Movement => m_Wrapper.m_InputPlayerAction_Movement;
        public InputAction @Crouch => m_Wrapper.m_InputPlayerAction_Crouch;
        public InputAction @Run => m_Wrapper.m_InputPlayerAction_Run;
        public InputAction @Reload => m_Wrapper.m_InputPlayerAction_Reload;
        public InputAction @Command => m_Wrapper.m_InputPlayerAction_Command;
        public InputAction @UnCommand => m_Wrapper.m_InputPlayerAction_UnCommand;
        public InputAction @HoldPosition => m_Wrapper.m_InputPlayerAction_HoldPosition;
        public InputAction @UnHoldPosition => m_Wrapper.m_InputPlayerAction_UnHoldPosition;
        public InputAction @CommandFriend1 => m_Wrapper.m_InputPlayerAction_CommandFriend1;
        public InputAction @CommandFriend2 => m_Wrapper.m_InputPlayerAction_CommandFriend2;
        public InputAction @ExitCommand => m_Wrapper.m_InputPlayerAction_ExitCommand;
        public InputAction @RegroupFriend => m_Wrapper.m_InputPlayerAction_RegroupFriend;
        public InputAction @Interact => m_Wrapper.m_InputPlayerAction_Interact;
        public InputAction @SkillButton => m_Wrapper.m_InputPlayerAction_SkillButton;
        public InputAction @Whistle => m_Wrapper.m_InputPlayerAction_Whistle;
        public InputAction @NightVision => m_Wrapper.m_InputPlayerAction_NightVision;
        public InputAction @Throw => m_Wrapper.m_InputPlayerAction_Throw;
        public InputAction @TakeCover => m_Wrapper.m_InputPlayerAction_TakeCover;
        public InputAction @ExitTakeCover => m_Wrapper.m_InputPlayerAction_ExitTakeCover;
        public InputAction @CommandFriend => m_Wrapper.m_InputPlayerAction_CommandFriend;
        public InputAction @ChangeCameraPlace => m_Wrapper.m_InputPlayerAction_ChangeCameraPlace;
        public InputAction @Immortalized => m_Wrapper.m_InputPlayerAction_Immortalized;
        public InputActionMap Get() { return m_Wrapper.m_InputPlayerAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputPlayerActionActions set) { return set.Get(); }
        public void AddCallbacks(IInputPlayerActionActions instance)
        {
            if (instance == null || m_Wrapper.m_InputPlayerActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InputPlayerActionActionsCallbackInterfaces.Add(instance);
            @Shooting.started += instance.OnShooting;
            @Shooting.performed += instance.OnShooting;
            @Shooting.canceled += instance.OnShooting;
            @SilentKill.started += instance.OnSilentKill;
            @SilentKill.performed += instance.OnSilentKill;
            @SilentKill.canceled += instance.OnSilentKill;
            @ChangingWeapon.started += instance.OnChangingWeapon;
            @ChangingWeapon.performed += instance.OnChangingWeapon;
            @ChangingWeapon.canceled += instance.OnChangingWeapon;
            @ChangePlayer.started += instance.OnChangePlayer;
            @ChangePlayer.performed += instance.OnChangePlayer;
            @ChangePlayer.canceled += instance.OnChangePlayer;
            @Scope.started += instance.OnScope;
            @Scope.performed += instance.OnScope;
            @Scope.canceled += instance.OnScope;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Command.started += instance.OnCommand;
            @Command.performed += instance.OnCommand;
            @Command.canceled += instance.OnCommand;
            @UnCommand.started += instance.OnUnCommand;
            @UnCommand.performed += instance.OnUnCommand;
            @UnCommand.canceled += instance.OnUnCommand;
            @HoldPosition.started += instance.OnHoldPosition;
            @HoldPosition.performed += instance.OnHoldPosition;
            @HoldPosition.canceled += instance.OnHoldPosition;
            @UnHoldPosition.started += instance.OnUnHoldPosition;
            @UnHoldPosition.performed += instance.OnUnHoldPosition;
            @UnHoldPosition.canceled += instance.OnUnHoldPosition;
            @CommandFriend1.started += instance.OnCommandFriend1;
            @CommandFriend1.performed += instance.OnCommandFriend1;
            @CommandFriend1.canceled += instance.OnCommandFriend1;
            @CommandFriend2.started += instance.OnCommandFriend2;
            @CommandFriend2.performed += instance.OnCommandFriend2;
            @CommandFriend2.canceled += instance.OnCommandFriend2;
            @ExitCommand.started += instance.OnExitCommand;
            @ExitCommand.performed += instance.OnExitCommand;
            @ExitCommand.canceled += instance.OnExitCommand;
            @RegroupFriend.started += instance.OnRegroupFriend;
            @RegroupFriend.performed += instance.OnRegroupFriend;
            @RegroupFriend.canceled += instance.OnRegroupFriend;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @SkillButton.started += instance.OnSkillButton;
            @SkillButton.performed += instance.OnSkillButton;
            @SkillButton.canceled += instance.OnSkillButton;
            @Whistle.started += instance.OnWhistle;
            @Whistle.performed += instance.OnWhistle;
            @Whistle.canceled += instance.OnWhistle;
            @NightVision.started += instance.OnNightVision;
            @NightVision.performed += instance.OnNightVision;
            @NightVision.canceled += instance.OnNightVision;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @TakeCover.started += instance.OnTakeCover;
            @TakeCover.performed += instance.OnTakeCover;
            @TakeCover.canceled += instance.OnTakeCover;
            @ExitTakeCover.started += instance.OnExitTakeCover;
            @ExitTakeCover.performed += instance.OnExitTakeCover;
            @ExitTakeCover.canceled += instance.OnExitTakeCover;
            @CommandFriend.started += instance.OnCommandFriend;
            @CommandFriend.performed += instance.OnCommandFriend;
            @CommandFriend.canceled += instance.OnCommandFriend;
            @ChangeCameraPlace.started += instance.OnChangeCameraPlace;
            @ChangeCameraPlace.performed += instance.OnChangeCameraPlace;
            @ChangeCameraPlace.canceled += instance.OnChangeCameraPlace;
            @Immortalized.started += instance.OnImmortalized;
            @Immortalized.performed += instance.OnImmortalized;
            @Immortalized.canceled += instance.OnImmortalized;
        }

        private void UnregisterCallbacks(IInputPlayerActionActions instance)
        {
            @Shooting.started -= instance.OnShooting;
            @Shooting.performed -= instance.OnShooting;
            @Shooting.canceled -= instance.OnShooting;
            @SilentKill.started -= instance.OnSilentKill;
            @SilentKill.performed -= instance.OnSilentKill;
            @SilentKill.canceled -= instance.OnSilentKill;
            @ChangingWeapon.started -= instance.OnChangingWeapon;
            @ChangingWeapon.performed -= instance.OnChangingWeapon;
            @ChangingWeapon.canceled -= instance.OnChangingWeapon;
            @ChangePlayer.started -= instance.OnChangePlayer;
            @ChangePlayer.performed -= instance.OnChangePlayer;
            @ChangePlayer.canceled -= instance.OnChangePlayer;
            @Scope.started -= instance.OnScope;
            @Scope.performed -= instance.OnScope;
            @Scope.canceled -= instance.OnScope;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Command.started -= instance.OnCommand;
            @Command.performed -= instance.OnCommand;
            @Command.canceled -= instance.OnCommand;
            @UnCommand.started -= instance.OnUnCommand;
            @UnCommand.performed -= instance.OnUnCommand;
            @UnCommand.canceled -= instance.OnUnCommand;
            @HoldPosition.started -= instance.OnHoldPosition;
            @HoldPosition.performed -= instance.OnHoldPosition;
            @HoldPosition.canceled -= instance.OnHoldPosition;
            @UnHoldPosition.started -= instance.OnUnHoldPosition;
            @UnHoldPosition.performed -= instance.OnUnHoldPosition;
            @UnHoldPosition.canceled -= instance.OnUnHoldPosition;
            @CommandFriend1.started -= instance.OnCommandFriend1;
            @CommandFriend1.performed -= instance.OnCommandFriend1;
            @CommandFriend1.canceled -= instance.OnCommandFriend1;
            @CommandFriend2.started -= instance.OnCommandFriend2;
            @CommandFriend2.performed -= instance.OnCommandFriend2;
            @CommandFriend2.canceled -= instance.OnCommandFriend2;
            @ExitCommand.started -= instance.OnExitCommand;
            @ExitCommand.performed -= instance.OnExitCommand;
            @ExitCommand.canceled -= instance.OnExitCommand;
            @RegroupFriend.started -= instance.OnRegroupFriend;
            @RegroupFriend.performed -= instance.OnRegroupFriend;
            @RegroupFriend.canceled -= instance.OnRegroupFriend;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @SkillButton.started -= instance.OnSkillButton;
            @SkillButton.performed -= instance.OnSkillButton;
            @SkillButton.canceled -= instance.OnSkillButton;
            @Whistle.started -= instance.OnWhistle;
            @Whistle.performed -= instance.OnWhistle;
            @Whistle.canceled -= instance.OnWhistle;
            @NightVision.started -= instance.OnNightVision;
            @NightVision.performed -= instance.OnNightVision;
            @NightVision.canceled -= instance.OnNightVision;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @TakeCover.started -= instance.OnTakeCover;
            @TakeCover.performed -= instance.OnTakeCover;
            @TakeCover.canceled -= instance.OnTakeCover;
            @ExitTakeCover.started -= instance.OnExitTakeCover;
            @ExitTakeCover.performed -= instance.OnExitTakeCover;
            @ExitTakeCover.canceled -= instance.OnExitTakeCover;
            @CommandFriend.started -= instance.OnCommandFriend;
            @CommandFriend.performed -= instance.OnCommandFriend;
            @CommandFriend.canceled -= instance.OnCommandFriend;
            @ChangeCameraPlace.started -= instance.OnChangeCameraPlace;
            @ChangeCameraPlace.performed -= instance.OnChangeCameraPlace;
            @ChangeCameraPlace.canceled -= instance.OnChangeCameraPlace;
            @Immortalized.started -= instance.OnImmortalized;
            @Immortalized.performed -= instance.OnImmortalized;
            @Immortalized.canceled -= instance.OnImmortalized;
        }

        public void RemoveCallbacks(IInputPlayerActionActions instance)
        {
            if (m_Wrapper.m_InputPlayerActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInputPlayerActionActions instance)
        {
            foreach (var item in m_Wrapper.m_InputPlayerActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InputPlayerActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InputPlayerActionActions @InputPlayerAction => new InputPlayerActionActions(this);

    // InputMenuAction
    private readonly InputActionMap m_InputMenuAction;
    private List<IInputMenuActionActions> m_InputMenuActionActionsCallbackInterfaces = new List<IInputMenuActionActions>();
    private readonly InputAction m_InputMenuAction_PauseGame;
    private readonly InputAction m_InputMenuAction_ExitSettingsMainMenu;
    private readonly InputAction m_InputMenuAction_SelectCommandButton;
    public struct InputMenuActionActions
    {
        private @PlayerActionInput m_Wrapper;
        public InputMenuActionActions(@PlayerActionInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseGame => m_Wrapper.m_InputMenuAction_PauseGame;
        public InputAction @ExitSettingsMainMenu => m_Wrapper.m_InputMenuAction_ExitSettingsMainMenu;
        public InputAction @SelectCommandButton => m_Wrapper.m_InputMenuAction_SelectCommandButton;
        public InputActionMap Get() { return m_Wrapper.m_InputMenuAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputMenuActionActions set) { return set.Get(); }
        public void AddCallbacks(IInputMenuActionActions instance)
        {
            if (instance == null || m_Wrapper.m_InputMenuActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InputMenuActionActionsCallbackInterfaces.Add(instance);
            @PauseGame.started += instance.OnPauseGame;
            @PauseGame.performed += instance.OnPauseGame;
            @PauseGame.canceled += instance.OnPauseGame;
            @ExitSettingsMainMenu.started += instance.OnExitSettingsMainMenu;
            @ExitSettingsMainMenu.performed += instance.OnExitSettingsMainMenu;
            @ExitSettingsMainMenu.canceled += instance.OnExitSettingsMainMenu;
            @SelectCommandButton.started += instance.OnSelectCommandButton;
            @SelectCommandButton.performed += instance.OnSelectCommandButton;
            @SelectCommandButton.canceled += instance.OnSelectCommandButton;
        }

        private void UnregisterCallbacks(IInputMenuActionActions instance)
        {
            @PauseGame.started -= instance.OnPauseGame;
            @PauseGame.performed -= instance.OnPauseGame;
            @PauseGame.canceled -= instance.OnPauseGame;
            @ExitSettingsMainMenu.started -= instance.OnExitSettingsMainMenu;
            @ExitSettingsMainMenu.performed -= instance.OnExitSettingsMainMenu;
            @ExitSettingsMainMenu.canceled -= instance.OnExitSettingsMainMenu;
            @SelectCommandButton.started -= instance.OnSelectCommandButton;
            @SelectCommandButton.performed -= instance.OnSelectCommandButton;
            @SelectCommandButton.canceled -= instance.OnSelectCommandButton;
        }

        public void RemoveCallbacks(IInputMenuActionActions instance)
        {
            if (m_Wrapper.m_InputMenuActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInputMenuActionActions instance)
        {
            foreach (var item in m_Wrapper.m_InputMenuActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InputMenuActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InputMenuActionActions @InputMenuAction => new InputMenuActionActions(this);
    public interface IInputPlayerActionActions
    {
        void OnShooting(InputAction.CallbackContext context);
        void OnSilentKill(InputAction.CallbackContext context);
        void OnChangingWeapon(InputAction.CallbackContext context);
        void OnChangePlayer(InputAction.CallbackContext context);
        void OnScope(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnCommand(InputAction.CallbackContext context);
        void OnUnCommand(InputAction.CallbackContext context);
        void OnHoldPosition(InputAction.CallbackContext context);
        void OnUnHoldPosition(InputAction.CallbackContext context);
        void OnCommandFriend1(InputAction.CallbackContext context);
        void OnCommandFriend2(InputAction.CallbackContext context);
        void OnExitCommand(InputAction.CallbackContext context);
        void OnRegroupFriend(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSkillButton(InputAction.CallbackContext context);
        void OnWhistle(InputAction.CallbackContext context);
        void OnNightVision(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnTakeCover(InputAction.CallbackContext context);
        void OnExitTakeCover(InputAction.CallbackContext context);
        void OnCommandFriend(InputAction.CallbackContext context);
        void OnChangeCameraPlace(InputAction.CallbackContext context);
        void OnImmortalized(InputAction.CallbackContext context);
    }
    public interface IInputMenuActionActions
    {
        void OnPauseGame(InputAction.CallbackContext context);
        void OnExitSettingsMainMenu(InputAction.CallbackContext context);
        void OnSelectCommandButton(InputAction.CallbackContext context);
    }
}
